name: Aegis CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
  repository_dispatch:
    types: [docs_updated]

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  # 1. Linting
  call-lint:
    uses: ./.github/workflows/linting.yml

  # 2. Build & Test
  call-tests:
    needs: call-lint
    uses: ./.github/workflows/build-and-test.yml

  # 3. Deploy Documentation (On push to main or docs update dispatch)
  call-docs:
    needs: call-tests
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'repository_dispatch')
    uses: ./.github/workflows/documentation.yml
